package via.sep2.startup;
/**
 * @author Troels, Mario
 */
public enum ViewType
{
  ADD_CUSTOMER,
  MANAGE_CUSTOMER,
  DINING_CUSTOMER,
  DINING_EMPLOYEE,
  DINING_MANAGE_CUSTOMER,
  DINING_MANAGE_EMPLOYEE,
  ADD_EMPLOYEE,
  MANAGE_EMPLOYEE,
  LOGIN,
  OVERVIEW_CUSTOMER,
  OVERVIEW_EMPLOYEE,
  OVERVIEW_MANAGER,
  REGISTER,
  UPDATE_PASSWORD,
  RESERVATION_CUSTOMER,
  RESERVATION_EMPLOYEE,
  RESERVATION_MANAGE_CUSTOMER,
  RESERVATION_MANAGE_EMPLOYEE,
  PRICE
}
